x-common-services:
  redis-node: &redis-node
    image: redis:8.2.1-bookworm

x-volumes:
  data: &vol-data
    driver: local

name: ${CLUSTER_ID:?error}

services:
  node-1:
    <<: *redis-node
    container_name: ${CLUSTER_ID:?error}-node-1
    hostname: ${CLUSTER_ID:?error}-node-1
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--cluster-announce-hostname", "${HOST_NAME:?error}", "--cluster-announce-port", "6379", "--cluster-announce-bus-port", "16379"]
    ports:
      - 6379:6379
      - 16379:16379
    environment:
      ANNOUNCED_HOST: ${HOST_NAME:?error}
      ANNOUNCED_PORT: 6379
    volumes:
      - node-data-1:/data
      - ./conf/nodes/1:/usr/local/etc/redis:rw
    extra_hosts:
      - "${HOST_NAME:?error}=${HOST_IP:?error}"

  node-2:
    <<: *redis-node
    container_name: ${CLUSTER_ID:?error}-node-2
    hostname: ${CLUSTER_ID:?error}-node-2
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--cluster-announce-hostname", "${HOST_NAME:?error}", "--cluster-announce-port", "6380", "--cluster-announce-bus-port", "16380"]
    ports:
      - 6380:6379
      - 16380:16379
    environment:
      ANNOUNCED_HOST: ${HOST_NAME:?error}
      ANNOUNCED_PORT: 6380
    volumes:
      - node-data-2:/data
      - ./conf/nodes/2:/usr/local/etc/redis:rw
    extra_hosts:
      - "${HOST_NAME:?error}=${HOST_IP:?error}"

  node-3:
    <<: *redis-node
    container_name: ${CLUSTER_ID:?error}-node-3
    hostname: ${CLUSTER_ID:?error}-node-3
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--cluster-announce-hostname", "${HOST_NAME:?error}", "--cluster-announce-port", "6381", "--cluster-announce-bus-port", "16381"]
    ports:
      - 6381:6379
      - 16381:16379
    environment:
      ANNOUNCED_HOST: ${HOST_NAME:?error}
      ANNOUNCED_PORT: 6381
    volumes:
      - node-data-3:/data
      - ./conf/nodes/3:/usr/local/etc/redis:rw
    extra_hosts:
      - "${HOST_NAME:?error}=${HOST_IP:?error}"

  node-4:
    <<: *redis-node
    container_name: ${CLUSTER_ID:?error}-node-4
    hostname: ${CLUSTER_ID:?error}-node-4
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--cluster-announce-hostname", "${HOST_NAME:?error}", "--cluster-announce-port", "6382", "--cluster-announce-bus-port", "16382"]
    ports:
      - 6382:6379
      - 16382:16379
    environment:
      ANNOUNCED_HOST: ${HOST_NAME:?error}
      ANNOUNCED_PORT: 6382
    volumes:
      - node-data-4:/data
      - ./conf/nodes/4:/usr/local/etc/redis:rw
    extra_hosts:
      - "${HOST_NAME:?error}=${HOST_IP:?error}"

  node-5:
    <<: *redis-node
    container_name: ${CLUSTER_ID:?error}-node-5
    hostname: ${CLUSTER_ID:?error}-node-5
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--cluster-announce-hostname", "${HOST_NAME:?error}", "--cluster-announce-port", "6383", "--cluster-announce-bus-port", "16383"]
    ports:
      - 6383:6379
      - 16383:16379
    environment:
      ANNOUNCED_HOST: ${HOST_NAME:?error}
      ANNOUNCED_PORT: 6383
    volumes:
      - node-data-5:/data
      - ./conf/nodes/5:/usr/local/etc/redis:rw
    extra_hosts:
      - "${HOST_NAME:?error}=${HOST_IP:?error}"

  node-6:
    <<: *redis-node
    container_name: ${CLUSTER_ID:?error}-node-6
    hostname: ${CLUSTER_ID:?error}-node-6
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--cluster-announce-hostname", "${HOST_NAME:?error}", "--cluster-announce-port", "6384", "--cluster-announce-bus-port", "16384"]
    ports:
      - 6384:6379
      - 16384:16379
    environment:
      ANNOUNCED_HOST: ${HOST_NAME:?error}
      ANNOUNCED_PORT: 6384
    volumes:
      - node-data-6:/data
      - ./conf/nodes/6:/usr/local/etc/redis:rw
    extra_hosts:
      - "${HOST_NAME:?error}=${HOST_IP:?error}"

networks:
  net:
    name: ${CLUSTER_ID:?error}
    driver: bridge

volumes:
  node-data-1: *vol-data
  node-data-2: *vol-data
  node-data-3: *vol-data
  node-data-4: *vol-data
  node-data-5: *vol-data
  node-data-6: *vol-data
